name: "Ruby on Rails CI"

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        ports:
          - "5432:5432"
        env:
          POSTGRES_DB: rails_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      RAILS_ENV: test
      DATABASE_URL: "postgres://root:password@localhost:5432/rails_test"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Ruby and gems
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Wait for PostgreSQL to be ready
        run: |
          for i in {1..60}; do
            pg_isready -h localhost -p 5432 && break
            echo "Waiting for PostgreSQL..."
            sleep 5
          done
        env:
          PGPASSWORD: postgres

      - name: Create PostgreSQL roles
        run: |
          psql -U postgres -c "CREATE ROLE root WITH LOGIN SUPERUSER PASSWORD 'password';"
          psql -U postgres -c "CREATE ROLE rails WITH LOGIN PASSWORD 'password';"
        env:
          PGPASSWORD: postgres

      - name: Set up database schema
        run: bin/rails db:schema:load

      - name: Run tests
        run: bin/rake
